# -- coding: utf-8 --**

"""
Created on 2025/10/08

@author: Ruoyu Chen
"""

import argparse

import os
import os
import json
import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image

from tqdm import tqdm

from sklearn import metrics
from utils import *
from visualization.visualization import add_value

import math

def parse_args():
    parser = argparse.ArgumentParser(description='Point Game')
    parser.add_argument("--test_txt", type=str, default="data_list/saliency-bench/test.txt")
    parser.add_argument('--explanation-dir', 
                        type=str, 
                        default='ckpt_vision/ckpts_clip_L14/best_epoch1-predict-label',
                        help='Save path for saliency maps generated by our methods.')
    args = parser.parse_args()
    return args

def read_list_file(list_path: str):
    items = []
    with open(list_path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            img_p, mask_p, label = line.split()
            items.append((img_p, mask_p, label))
    return items

def build_label_map(list_file: str):
    labels = [lab for _, _, lab in read_list_file(list_file)]
    labels = sorted(list(set(labels)))
    return {lab: i for i, lab in enumerate(labels)}

def main(args):
    with open(args.test_txt, "r") as f:
        items = [line.strip().split() for line in f if line.strip()]
    
    point_game_tp_scores = []
    point_game_wp_scores = []
    
    label_to_idx = build_label_map(args.test_txt)
    idx_to_label = {v:k for k,v in label_to_idx.items()}
    
    for img_path, mask_path, label in tqdm(items):
        # Load mask
        gt_mask = np.load(mask_path)
        
        label_id = label_to_idx[label]
       
        # gt_mask = (gt_mask > 128).astype(np.uint8)
        
        # Load explanation
        explanation_path = os.path.join(args.explanation_dir+"/npy", os.path.basename(img_path).replace('.png', '.npy'))
        json_file_path = os.path.join(args.explanation_dir+"/json", os.path.basename(img_path).replace('.png', '.json'))
        
        if not os.path.exists(explanation_path):
            # print(f"Explanation file not found: {explanation_path}")
            continue
        
        S_set = np.load(explanation_path)
        with open(json_file_path, 'r', encoding='utf-8') as f:
            saved_json_file = json.load(f)
        
        # Point Game Mask
        total_S_ones = (S_set[0] > 0).astype(np.uint8).sum()
        overlap = (S_set[0].squeeze() * gt_mask).sum()
        ratio = overlap / total_S_ones
        # print(saved_json_file["predict_label"], label)
        if ratio > 0.2:
            if saved_json_file["predict_label"] == label_id:
                point_game_tp_scores.append(1)
            else:
                point_game_wp_scores.append(1)
        else: 
            if saved_json_file["predict_label"] == label_id:
                point_game_tp_scores.append(0)
            else:
                point_game_wp_scores.append(0)
    # print(point_game_tp_scores)
    print(f"Point Game Score (True Predict {len(point_game_tp_scores)}): {np.mean(point_game_tp_scores):.4f}")
    print(f"Point Game Score (Wrong Predict {len(point_game_wp_scores)}): {np.mean(point_game_wp_scores):.4f}")
        
if __name__ == "__main__":
    args = parse_args()
    main(args)