# -- coding: utf-8 --**

"""
Created on 2025/10/08

@author: Ruoyu Chen
"""

import argparse

import os
import os
import json
import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image

from tqdm import tqdm

from sklearn import metrics
from utils import *
from visualization.visualization import add_value

import math

def parse_args():
    parser = argparse.ArgumentParser(description='Point Game')
    parser.add_argument("--test_txt", type=str, default="data_list/imagenet-s919/test_one_per_class.txt")
    parser.add_argument('--explanation-dir', 
                        type=str, 
                        default='ckpt_vision_imagenets/ckpts_vit_b16_imnet_/best_epoch2',
                        help='Save path for saliency maps generated by our methods.')
    args = parser.parse_args()
    return args

def main(args):
    print(args.explanation_dir)
    with open(args.test_txt, "r") as f:
        items = [line.strip().split() for line in f if line.strip()]
    
    point_game_scores = []
    
    for img_path, mask_path, label in tqdm(items):
        # Load mask
        gt_mask = cv2.resize(cv2.imread(mask_path), (224,224)) # np.load(mask_path)
        gt_mask = (gt_mask.sum(-1) > 0).astype(np.uint8)
       
        # gt_mask = (gt_mask > 128).astype(np.uint8)
        
        # Load explanation
        explanation_path = os.path.join(args.explanation_dir+"/npy", os.path.basename(img_path).replace('.JPEG', '.npy'))
        json_file_path = os.path.join(args.explanation_dir+"/json", os.path.basename(img_path).replace('.JPEG', '.json'))
        
        if not os.path.exists(explanation_path):
            print(f"Explanation file not found: {explanation_path}")
            continue
        
        S_set = np.load(explanation_path)
        with open(json_file_path, 'r', encoding='utf-8') as f:
            saved_json_file = json.load(f)
        
        # Point Game Mask
        total_S_ones = (S_set[0] > 0).astype(np.uint8).sum()
        overlap = (S_set[0].squeeze() * gt_mask).sum()
        ratio = overlap / total_S_ones
        if ratio > 0.2:
            point_game_scores.append(1)
        else: 
            point_game_scores.append(0)
        
    print(f"Point Game Score: {np.mean(point_game_scores):.4f}")
        
        
if __name__ == "__main__":
    args = parse_args()
    main(args)