# -*- coding: utf-8 -*-

"""
Created on 2025/10/13

@author: Ruoyu Chen
"""

import argparse

import scipy
import os
import cv2
import json
import imageio
import numpy as np
from PIL import Image
# import supervision as sv
import torch

import matplotlib
from matplotlib import pyplot as plt

from torchvision.ops import box_convert

from tqdm import tqdm
from utils import *

from visualization.visualization import *

from sklearn import metrics

def parse_args():
    parser = argparse.ArgumentParser(description='Point Game')
    parser.add_argument("--test_txt", type=str, default="test.txt")
    parser.add_argument('--explanation-dir', 
                        type=str, 
                        default='interpretation_results/CLIP-baseline-64',
                        help='Save path for saliency maps generated by our methods.')
    args = parser.parse_args()
    return args

def main(args):
    print(args.explanation_dir)
    
    with open(args.test_txt, "r") as f:
        items = [line.strip().split() for line in f if line.strip()]
    
    json_root_file = os.path.join(args.explanation_dir, "json")
    npy_root_file = os.path.join(args.explanation_dir, "npy")
    
    visualization_path = os.path.join(args.explanation_dir, "saliency_map")
    mkdir(visualization_path)
        
    for img_path, mask_path, label in tqdm(items):
        # Load mask
        gt_mask = np.load(mask_path)
        
        # Load explanation
        explanation_path = os.path.join(args.explanation_dir+"/npy", os.path.basename(img_path).replace('.png', '.npy'))
        json_file_path = os.path.join(args.explanation_dir+"/json", os.path.basename(img_path).replace('.png', '.json'))
        
        if not os.path.exists(explanation_path):
            print(f"Explanation file not found: {explanation_path}")
            continue
        
        S_set = np.load(explanation_path)
        with open(json_file_path, 'r', encoding='utf-8') as f:
            saved_json_file = json.load(f)
            
        image = cv2.imread(img_path)
        
        attribution_map, _ = add_value(S_set, saved_json_file)
        vis_saliency_map, heatmap = gen_cam(img_path, norm_image(attribution_map[:,:,0]))
        
        vis_saliency_map_with_annotation = overlay_mask_with_white_edge(
            vis_saliency_map, 
            gt_mask, 
            alpha=0.2)
        
        cv2.imwrite(
            os.path.join(visualization_path, os.path.basename(img_path)),
            vis_saliency_map_with_annotation
        )
        # break
    
if __name__ == "__main__":
    args = parse_args()
    main(args)